# Generated by Django 4.2 on 2024-04-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('autor', models.CharField(default='anonimo', max_length=100)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.articulo')),
            ],
        ),
    ]
